### ISSUE TITLE
Support: Add support of mirror direction between gitee and github.

### ISSUE THREAD

**Issue by Yikun** [Yikun/gitee-mirror-action#2]
Now we only support mirror the Github to Gitee, we can also support github to gitee:

```yaml
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/gitee-mirror-action@master
  with:
    private_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    github_to_gitee: False
    github_org: kunpengcompute
    gitee_org: kunpengcompute
```

We could a `github_to_gitee` arg to make the sync direction can be set flexiablely.
